<a href="https://colab.research.google.com/github/Angel353/Act_5_GPPT/blob/main/Actividad5Sebas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Cargamos librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
#cargar archivo csv desde google colab
from google.colab import files
files.upload()

In [ ]:
df = pd.read_excel('CredicelModel2.xlsx')
df

In [ ]:
df.info()

In [ ]:
#Corroboramos valores nulos
ValoresNulos = df.isnull().sum()
ValoresNulos

Modelo 4

In [ ]:
#declaramos variables depdendientes y independendientes
Vars_Indep=df[['costo_total','puntos','edad_cliente']]
Vars_Dep=df['riesgo_cat']

In [ ]:
#redefinimos las variables
X=Vars_Indep
y=Vars_Dep

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=None)

In [ ]:
#se escalan todos los datos
escalar = StandardScaler()


In [ ]:
#Para relaizar el escalamiento de las variables X tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#definimos el algopritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred= algoritmo.predict(X_test)
y_pred

array(['Hay Riesgo', 'No hay Riesgo', 'No hay Riesgo', ...,
       'No hay Riesgo', 'No hay Riesgo', 'No hay Riesgo'], dtype=object)

In [ ]:
#verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test,y_pred)
print('Matriz de Confusion:')
print(matriz)

Matriz de Confusion:
[[1999  422]
 [1215  911]]


In [ ]:
#calculo de la precision del modelo del si

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('Precision del modelo')
print(precision)

Precision del modelo
0.6219663970130678


In [ ]:
#calculo de la precision del modelo no

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label='No hay Riesgo')
print('Precision del modelo')
print(precision)

Precision del modelo
0.6834208552138035


In [ ]:
#calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test,y_pred)
print('exactitud del modelo')
print(exactitud)

exactitud del modelo
0.6399824059819661


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.825691862866584


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="No hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.42850423330197557


In [ ]:
#el f1 que es la mezcal de precision y sensibilidad

from sklearn.metrics import f1_score

puntajef1= f1_score(y_test,y_pred, average="binary", pos_label="Hay Riesgo")
print("puntaje f1 del modelo")
print(puntajef1)

puntaje f1 del modelo
0.6950151867071646


Modelo 5

In [ ]:
#declaramos variables depdendientes y independendientes
Vars_Indep=df[['costo_total','enganche','precio',]]
Vars_Dep=df['riesgo_cat']

In [ ]:
#redefinimos las variables
X=Vars_Indep
y=Vars_Dep

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=None)

In [ ]:
#se escalan todos los datos
escalar = StandardScaler()


In [ ]:
#Para relaizar el escalamiento de las variables X tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#definimos el algopritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred= algoritmo.predict(X_test)
y_pred

array(['Hay Riesgo', 'Hay Riesgo', 'Hay Riesgo', ..., 'No hay Riesgo',
       'Hay Riesgo', 'Hay Riesgo'], dtype=object)

In [ ]:
#verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test,y_pred)
print('Matriz de Confusion:')
print(matriz)

Matriz de Confusion:
[[2935  726]
 [1031 2129]]


In [ ]:
#calculo de la precision del modelo del si

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('Precision del modelo')
print(precision)

Precision del modelo
0.7400403429147756


In [ ]:
#calculo de la precision del modelo del no

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label='No hay Riesgo')
print('Precision del modelo')
print(precision)

Precision del modelo
0.7457092819614711


In [ ]:
#calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test,y_pred)
print('exactitud del modelo')
print(exactitud)

exactitud del modelo
0.7424131359038264


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.8016935263589183


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="No hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.6737341772151899


In [ ]:
#el f1 que es la mezcal de precision y sensibilidad

from sklearn.metrics import f1_score

puntajef1= f1_score(y_test,y_pred, average="binary", pos_label="Hay Riesgo")
print("puntaje f1 del modelo")
print(puntajef1)

puntaje f1 del modelo
0.7711830799735625


Modelo 6

In [ ]:
#declaramos variables depdendientes y independendientes
Vars_Indep=df[['precio','enganche','puntos']]
Vars_Dep=df['riesgo_cat']

In [ ]:
#redefinimos las variables
X=Vars_Indep
y=Vars_Dep

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=None)

In [ ]:
#se escalan todos los datos
escalar = StandardScaler()


In [ ]:
#Para relaizar el escalamiento de las variables X tanto de entrenamiento como de prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#definimos el algopritmo
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train,y_train)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred= algoritmo.predict(X_test)
y_pred

array(['No hay Riesgo', 'Hay Riesgo', 'Hay Riesgo', ..., 'Hay Riesgo',
       'Hay Riesgo', 'Hay Riesgo'], dtype=object)

In [ ]:
#verificamos la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test,y_pred)
print('Matriz de Confusion:')
print(matriz)

Matriz de Confusion:
[[3028  590]
 [1111 2092]]


In [ ]:
#calculo de la precision del modelo del si

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('Precision del modelo')
print(precision)

Precision del modelo
0.7315776757670935


In [ ]:
#calculo de la precision del modelo no

from sklearn.metrics import precision_score

precision=precision_score(y_test,y_pred,average="binary",pos_label="No hay Riesgo")
print('Precision del modelo')
print(precision)

Precision del modelo
0.7800149142431022


In [ ]:
#calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test,y_pred)
print('exactitud del modelo')
print(exactitud)

exactitud del modelo
0.7506230757953379


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="Hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.8369264787175235


In [ ]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred,average="binary",pos_label="No hay Riesgo")
print('sensibilidad')
print(sensibilidad)

sensibilidad
0.653137683421792


In [ ]:
#el f1 que es la mezcal de precision y sensibilidad

from sklearn.metrics import f1_score

puntajef1= f1_score(y_test,y_pred, average="binary", pos_label="Hay Riesgo")
print("puntaje f1 del modelo")
print(puntajef1)

puntaje f1 del modelo
0.7735576291234065
